name: RELEASE-KBCLI-YUM-TAG

on:
  push:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "The release version of kbcli"
        type: string
        required: true
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  CLI_NAME: "kbcli"
  TAG_NAME: "v0.5.1"

jobs:
  update-version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux-amd64, linux-arm64]
    steps:
      - uses: actions/checkout@v3
      - name: install lib
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libbtrfs-dev \
            libdevmapper-dev
          sudo apt-get install -y rpm build-essential
          sudo apt-get install -y createrepo-c
          cd ${{ matrix.os }}
          curl -O -L https://github.com/apecloud/kbcli/releases/download/${{ env.TAG_NAME }}/${{ env.CLI_NAME }}-${{ matrix.os }}-${{ env.TAG_NAME }}.tar.gz
          echo "CLI_FILENAME=${{ env.CLI_NAME }}-${{ matrix.os }}-${{ env.TAG_NAME }}" >> $GITHUB_ENV
          ls

      - name: make RPM package
        if: matrix.os == 'linux-amd64' || matrix.os == 'linux-arm64'
        run: |
          cd ${{ matrix.os }}
          cp ${{ env.CLI_FILENAME }}.tar.gz rpmbuild/SOURCES/
          cp ${{ github.workspace }}/.github/utils/kbcli.spec rpmbuild/SPECS/
          mv rpmbuild/SPECS/kbcli.spec rpmbuild/SPECS/kbcli-${{ env.TAG_NAME }}.spec
          sed -i 's/^Source0:.*/Source0: ${{ env.CLI_FILENAME }}.tar.gz/' rpmbuild/SPECS/kbcli-${{ env.TAG_NAME }}.spec
          sed -i 's/^Version:.*/Version: ${{ env.TAG_NAME }}/' rpmbuild/SPECS/kbcli-${{ env.TAG_NAME }}.spec
          sed -i 's/^%setup.*/%setup -q -n ${{ matrix.os }}/' rpmbuild/SPECS/kbcli-${{ env.TAG_NAME }}.spec
          cp -r rpmbuild /home/runner/
          rpmbuild --target ${{ matrix.os == 'linux-amd64' && 'x86_64' || 'aarch64' }} -ba rpmbuild/SPECS/kbcli-${{ env.TAG_NAME }}.spec

      - name: build RPM repo
        if: matrix.os == 'linux-amd64' || matrix.os == 'linux-arm64'
        run: |
          cd ${{ matrix.os }}
          cp /home/runner/rpmbuild/RPMS/${{ matrix.os == 'linux-amd64' && 'x86_64' || 'aarch64' }}/${{ env.CLI_NAME }}-${{ env.TAG_NAME }}-1.${{ matrix.os == 'linux-amd64' && 'x86_64' || 'aarch64' }}.rpm ./
          createrepo_c -pdo ./ ./
          createrepo_c --update ./

          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "update rpm repo"
          git pull
          git config pull.rebase false
          git pull

      - name: Push kbcli yum repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true