name: RELEASE-KBCLI-YUM-TAG

on:
  push:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "The release version of kbcli"
        type: string
        required: true
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  CLI_NAME: "kbcli"
  TAG_NAME: "v0.5.1"
#  TAG_NAME: ${{ github.event.inputs.VERSION }}
  CLI_FILENAME: "kbcli-linux-amd64-v0.6.0-alpha.8"


jobs:
  update-version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux-amd64, linux-arm64]
    steps:
      - uses: actions/checkout@v3
      - name: install lib
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libbtrfs-dev \
            libdevmapper-dev
          sudo apt-get install -y rpm build-essential
          sudo apt-get install -y createrepo-c

      - name: make RPM package
        if: matrix.os == 'linux-amd64' || matrix.os == 'linux-arm64'
        run: |
          curl -O -L https://github.com/apecloud/kbcli/releases/download/${{ env.TAG_NAME }}/${{ env.CLI_NAME }}-${{ matrix.os }}-${{ env.TAG_NAME }}.tar.gz
          pwd
          ls
          cp ${{ env.CLI_FILENAME }}.tar.gz rpmbuild/SOURCES/
          cp ${{ github.workspace }}/.github/utils/kbcli.spec rpmbuild/SPECS/
          sed -i 's/^Source0:.*/Source0: ${{ env.CLI_FILENAME }}.tar.gz/' rpmbuild/SPECS/kbcli.spec
          sed -i 's/^Version:.*/Version: ${{ env.TAG_NAME }}/' rpmbuild/SPECS/kbcli.spec
          sed -i 's/^%setup.*/%setup -q -n ${{ matrix.os }}/' rpmbuild/SPECS/kbcli.spec
          if [ "${{ matrix.os }}" = "linux-amd64" ]; then
            rpmbuild --target x86_64 -ba rpmbuild/SPECS/kbcli.spec
          elif [ "${{ matrix.os }}" = "linux-arm64" ]; then
            rpmbuild --target aarch64 -ba rpmbuild/SPECS/kbcli.spec
          fi

      - name: build RPM repo
        if: matrix.os == 'linux-amd64' || matrix.os == 'linux-arm64'
        run: |
          cp /home/runner/rpmbuild/RPMS/${{ matrix.os == 'linux-amd64' && 'x86_64' || 'aarch64' }}/${{ env.CLI_NAME }}-${{ env.TAG_NAME }}-1.${{ matrix.os == 'linux-amd64' && 'x86_64' || 'aarch64' }}.rpm ./
          createrepo_c -pdo ./ ./
          createrepo_c --update ./

          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "update rpm repo"

      - name: Push kbcli yum repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          branch: ${{ github.ref }}