name: RELEASE-YUM-KBCLI

on:
  push:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "release kbcli yum repo "
        type: string
        required: true
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  CLI_NAME: "kbcli"
  TAG_NAME: "v0.5.2"

jobs:
  release-yum-kbcli-amd:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux-amd64]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: install lib
        run: |
          bash ${{ github.workspace }}/.github/utils/utils.sh \
                  --os ${{ matrix.os }} \
                  --tag-name ${{ env.TAG_NAME }} \
                  --cli-name ${{ env.CLI_NAME }} \
                  --root-dir "/home/runner" \
                  --work-space ${{ github.workspace }}
  
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "update rpm repo"

      - name: Push kbcli yum repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          branch: "main"
          force: true

  release-yum-kbcli-arm:
    runs-on: ubuntu-latest
    needs: release-yum-kbcli-amd
    strategy:
      fail-fast: false
      matrix:
        os: [linux-arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - name: install lib
        run: |
          bash ${{ github.workspace }}/.github/utils/utils.sh \
                  --os ${{ matrix.os }} \
                  --tag-name ${{ env.TAG_NAME }} \
                  --cli-name ${{ env.CLI_NAME }} \
                  --root-dir "/home/runner" \
                  --work-space ${{ github.workspace }}

          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "update rpm repo"

      - name: Push kbcli yum repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          branch: "main"
          force: true

